name: "Update nixpkg"
on:
  workflow_dispatch:
    inputs:
      pkg:
        description: Nix package
        required: true
        type: string
      currVer:
        description: Current version
        required: true
        type: string
      newVer:
        description: New version
        required: true
        type: string
        
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: nix-community/nixpkgs-update
    - uses: cachix/install-nix-action@v30
    # - uses: cachix/cachix-action@v15
    #   with:
    #     name: nixpkgs-update
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
    - run: ls -l ./result
    - run: ls -l ./result/bin
    - run: ./result/bin/nixpkgs-update help
