name: "Updat nixpkg"
on:
  workflow_dispatch:
    inputs:
      pkg:
        description: Nix package
        required: true
        type: string
      currVer:
        description: Current version
        required: true
        type: string
      newVer:
        description: New version
        required: true
        type: string
        
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - run: nix build
    - run: ls -l
