name: "Update nixpkg"
on:
  workflow_dispatch:
    inputs:
      pkg:
        description: Nix package
        required: true
        type: string
      currVer:
        description: Current version
        required: true
        type: string
      newVer:
        description: New version
        required: true
        type: string
        
jobs:
  update-nixpkgs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: nix-community/nixpkgs-update
    - uses: cachix/install-nix-action@v30
      with:
          extra_nix_config: |
            experimental-features = nix-command flakes
    # - uses: cachix/cachix-action@v15
    #   with:
    #     name: nixpkgs-update
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --accept-flake-config
    - run: ./result/bin/nixpkgs-update --help || true
    - run: ./result/bin/nixpkgs-update update --help || true
    - run: ./result/bin/nixpkgs-update update "${{ inputs.pkg }} ${{ inputs.currVer }} ${{ inputs.newVer }}"
